site_name: CS 152 Data Structures PyDocs Reference Implementation Documentation

theme:
  name: "material"

plugins:
- mkdocstrings:
    handlers:
      python:
        paths: [datastructures]

nav:
 - Data Structures PyDocs: index.md
 - Array: array.md
 - Array2D: array2d.md