site_name: PyDocs Reference Implementation Documentation for CS 152 Data Structures and CS 351 Algorithms @ Willamette University

theme:
  name: "material"

plugins:
- mkdocstrings:
    handlers:
      python:
        paths: [datastructures]
        
- mkdocs-simple-hooks:
    hooks:
      on_post_build: "docs.hooks:copy_get"

markdown_extensions:
  - attr_list

nav:
 - Data Structures PyDocs: index.md
 - Array: array.md
 - AVL Tree: iavltree.md
#  - Array2D: array2d.md
#  - LinkedList: linked_list.md
#  - Stacks and Queues: stacks_queues.md
#  - HashMap: hash_map.md
#  - Graph: graph.md