site_name: PyDocs Reference Implementation Documentation for CS 152 Data Structures and CS 351 Algorithms @ Willamette University

theme:
  name: "material"

plugins:
- mkdocstrings:
    handlers:
      python:
        paths: [src/datastructures]
        
- mkdocs-simple-hooks:
    hooks:
      on_post_build: "docs.hooks:copy_get"

markdown_extensions:
  - attr_list

nav:
 - Data Structures PyDocs: index.md
 - Bag: bag.md
 - Array: array.md
 - Array2D: array2d.md
 - ArrayStack: arraystack.md
 - CircularQueue: circularqueue.md
 - LinkedList: linkedlist.md
 - ListStack: liststack.md
 - Deque: deque.md 

 
#  - Array2D: array2d.md
#  - LinkedList: linked_list.md
#  - Stack: stack.md
#  - Queue: queue.md
#  - HashMap: hashmap.md
#  - AVL Tree: iavltree.md
#  - Stacks and Queues: stacks_queues.md
#  - HashMap: hash_map.md
#  - Graph: graph.md